# Confirm shared object copying when building the Python package
# https://github.com/single-cell-data/TileDB-SOMA/pull/1937

name: Python SO copying

on:
  push:
    paths:
      - '.github/workflows/python-so-copying.yml'
      - 'apis/python/**'
      - 'libtiledbsoma/cmake/**'
  pull_request:
    paths:
      - '.github/workflows/python-so-copying.yml'
      - 'apis/python/**'
      - 'libtiledbsoma/cmake/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - run: uname -a
      - name: Setup
        run: |
          apt-get update
          apt-get install --yes git python-is-python3 python3 python3-pip python3-venv unzip wget
      - uses: actions/checkout@v4
      - name: Setup Python
        run: |
          python --version
          python -m venv ./venv-soma
          source ./venv-soma/bin/activate
          pip install --prefer-binary cmake pybind11-global typeguard sparse wheel
