# Confirm shared object copying when building the Python package
# https://github.com/single-cell-data/TileDB-SOMA/pull/1937

name: Python SO copying

on:
  push:
    paths:
      - '.github/workflows/python-so-copying.yml'
      - 'apis/python/**'
      - 'libtiledbsoma/cmake/**'
  pull_request:
    paths:
      - '.github/workflows/python-so-copying.yml'
      - 'apis/python/**'
      - 'libtiledbsoma/cmake/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
      - run: uname -a
      - name: Setup
        run: |
          apt-get update
          apt-get install --yes git python-is-python3 python3 python3-pip python3-venv unzip wget
          python --version
      - run: git log -n 1 --oneline
